steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cashguard:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cashguard:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/cashguard']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cashguard'
      - '--image=gcr.io/$PROJECT_ID/cashguard:$COMMIT_SHA'
      - '--region=us-east5'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/cashguard'
